name: CI

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/main'
        uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
        env:
          DYNAWO_VERSION: 1.4.0
          HADES2_FAMILY_VERSION: 6.9.0
          HADES2_VERSION: 6.9.0.2
        with:
          name: gridsuite/java-simulator
          username: gridsuiteci
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildargs: DYNAWO_VERSION,HADES2_FAMILY_VERSION,HADES2_VERSION
          tags: "2.0.0"
